alter session set "_ORACLE_SCRIPT"= true;


--
--  Eliminación de objetos creadas si existen
--

/*

alter session set "_ORACLE_SCRIPT"= true;
DROP USER usuario1 CASCADE;
DROP ROLE admin_role;

*/



--
--  Parte I: Creación de Rol
--


-- Creación de Rol específico a utilizar
CREATE ROLE admin_role;

-- Dar acceso a crear los siguientes recursos a Admin_Role
GRANT CREATE SESSION, CREATE TRIGGER, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE SEQUENCE TO admin_role;

-- Dar accesos a Any Table a admin_role
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO admin_role;

/*
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_CANTONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_CATEGORIAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DETALLEVENTAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DEVOLUCIONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DIRECCIONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DISTRITOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_EMPLEADOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_ESTADOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_FACTURAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_INVENTARIOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_MARCASPRODUCTO_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_METODOSPAGO_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PAISES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PRODUCTOPROVEEDOR_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PRODUCTOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PROVEEDORES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PROVINCIAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_ROLES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_SUCURSALES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_VENTAS_TB TO admin_role;
*/

CREATE USER usuario1 IDENTIFIED BY "123";
GRANT admin_role to usuario1;
ALTER USER usuario1 QUOTA UNLIMITED ON USERS;

