
--
--      Creación de tablas
--

CREATE TABLE FIDE_ESTADOS_TB(
    idEstado NUMBER 
    CONSTRAINT FIDE_ESTADOS_ID_ESTADO_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100));
    ---(Exito)

CREATE TABLE FIDE_CATEGORIAS_TB(
    idCategoria  NUMBER 
    CONSTRAINT FIDE_CATEGORIAS_ID_CATEGORIA_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    Descripcion VARCHAR2(1000),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_CATEGORIAS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
   
CREATE TABLE FIDE_PAISES_TB(
    idPais NUMBER 
    CONSTRAINT FIDE_PAIS_ID_PAIS_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_PAISES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_PROVINCIAS_TB(
    idProvincia NUMBER 
    CONSTRAINT FIDE_PROVINCIA_ID_PROVINCIA_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idPais NUMBER, 
    CONSTRAINT FIDE_PROVINCIAS_ID_PAIS_FOREIGN_KEY FOREIGN KEY (idPais) REFERENCES FIDE_PAISES_TB(idPais),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_PROVINCIAS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_CANTONES_TB(
    idCanton NUMBER 
    CONSTRAINT FIDE_CANTONES_ID_CANTON_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idProvincia NUMBER, 
    CONSTRAINT FIDE_CANTONES_ID_PROVINCIA_FOREIGN_KEY FOREIGN KEY (idProvincia) REFERENCES FIDE_PROVINCIAS_TB(idProvincia),
    FECHA_CREACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_CANTONES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_DISTRITOS_TB(
    idDistrito NUMBER 
    CONSTRAINT FIDE_DISTRITOS_ID_DISTRITO_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idCanton NUMBER, 
    CONSTRAINT FIDE_DISTRITOS_ID_CANTON_FOREIGN_KEY FOREIGN KEY (idCanton) REFERENCES FIDE_CANTONES_TB(idCanton),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_DISTRITOS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_DIRECCIONES_TB(
    idDireccion NUMBER 
    CONSTRAINT FIDE_DIRECCIONES_ID_DIRECCION_IDX PRIMARY KEY,
    idPais NUMBER, 
    CONSTRAINT FIDE_DIRECCIONES_ID_PAIS_FOREIGN_KEY FOREIGN KEY(idPais) REFERENCES FIDE_PAISES_TB(idPais),
    idProvincia NUMBER, 
    CONSTRAINT FIDE_DIRECCIONES_ID_PROVINCIA_FOREIGN_KEY FOREIGN KEY(idProvincia) REFERENCES FIDE_PROVINCIAS_TB(idProvincia),
    idCanton NUMBER, 
    CONSTRAINT FIDE_DIRECCIONES_ID_CANTON_FOREIGN_KEY FOREIGN KEY(idCanton) REFERENCES FIDE_CANTONES_TB(idCanton),
    idDistrito NUMBER, 
    CONSTRAINT FIDE_DIRECCIONES_ID_DISTRITO_FOREIGN_KEY FOREIGN KEY(idDistrito) REFERENCES FIDE_DISTRITOS_TB(idDistrito),
    direccionExacta VARCHAR2(1000),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_DIRECCIONES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
  
CREATE TABLE FIDE_PROVEEDORES_TB(
    idProveedor NUMBER 
    CONSTRAINT FIDE_PROVEEDORES_ID_PROVEEDOR_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idDireccion NUMBER, 
    CONSTRAINT FIDE_PROVEEDORES_ID_DIRECCION_FOREIGN_KEY FOREIGN KEY(idDireccion) REFERENCES FIDE_DIRECCIONES_TB(idDireccion),
    Telefono NUMBER,
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_PROVEEDORES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_MARCASPRODUCTO_TB(
    idMarca NUMBER 
    CONSTRAINT FIDE_MARCASPRODUCTO_TB_ID_MARCA_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_MARCASPRODUCTO_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_PRODUCTOS_TB(
    idProducto NUMBER 
    CONSTRAINT FIDE_PRODUCTOS_ID_PRODUCTO_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    Precio NUMBER(10,2),
    idCategoria NUMBER, 
    CONSTRAINT FIDE_PRODUCTOS_ID_CATEGORIA_FOREIGN_KEY FOREIGN KEY(idCategoria) REFERENCES FIDE_CATEGORIAS_TB(idCategoria),
    idEstado NUMBER, 
    CONSTRAINT FIDE_PRODUCTOS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    idMarca NUMBER, 
    CONSTRAINT FIDE_PRODUCTOS_ID_MARCA_FOREIGN_KEY FOREIGN KEY(idMarca) REFERENCES FIDE_MARCASPRODUCTO_TB(idMarca),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100));
    ---(Exito)

CREATE TABLE FIDE_PRODUCTOPROVEEDOR_TB(
    idProducto NUMBER, 
    idProveedor NUMBER, 
    horarioEntrega VARCHAR2(1000),
    precioCompra NUMBER(10,2),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_PRODUCTOPROVEEDOR_ID_PRODUCTO_ID_PROVEEDOR_IDX PRIMARY KEY (idProducto, idProveedor),
    CONSTRAINT FIDE_PRODUCTOPROVEEDOR_ID_PRODUCTO_FOREIGN_KEY FOREIGN KEY(idProducto) REFERENCES FIDE_PRODUCTOS_TB(idProducto),
    CONSTRAINT FIDE_PRODUCTOPROVEEDOR_ID_PROVEEDOR_FOREIGN_KEY FOREIGN KEY(idProveedor) REFERENCES FIDE_PROVEEDORES_TB(idProveedor),
    CONSTRAINT FIDE_PRODUCTOPROVEEDOR_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_SUCURSALES_TB(
    idSucursal NUMBER 
    CONSTRAINT FIDE_SUCURSALES_ID_SUCURSAL_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idDireccion NUMBER, 
    CONSTRAINT FIDE_SUCURSALES_ID_DIRECCION_FOREIGN_KEY FOREIGN KEY(idDireccion) REFERENCES FIDE_DIRECCIONES_TB(idDireccion),
    horaApertura VARCHAR2(200),
    horaCierre VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_SUCURSALES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_INVENTARIOS_TB(
    idInventario NUMBER 
    CONSTRAINT FIDE_INVENTARIOS_ID_INVENTARIO_IDX PRIMARY KEY,
    idProducto NUMBER, 
    CONSTRAINT FIDE_INVENTARIOS_ID_PRODUCTO_FOREIGN_KEY FOREIGN KEY(idProducto) REFERENCES FIDE_PRODUCTOS_TB(idProducto),
    Cantidad NUMBER,
    ultimaActualizacion DATE,
    idSucursal NUMBER, 
    CONSTRAINT FIDE_INVENTARIOS_ID_SUCURSAL_FOREIGN_KEY FOREIGN KEY(idSucursal) REFERENCES FIDE_SUCURSALES_TB(idSucursal),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_INVENTARIOS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)

CREATE TABLE FIDE_EMPLEADOS_TB(
    idEmpleado NUMBER 
    CONSTRAINT FIDE_EMPLEADOS_ID_EMPLEADO_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idSucursal NUMBER, 
    CONSTRAINT FIDE_EMPLEADOS_ID_SUCURSAL_FOREIGN_KEY FOREIGN KEY(idSucursal) REFERENCES FIDE_SUCURSALES_TB(idSucursal),
    Puesto VARCHAR2(200),
    idDireccion NUMBER, 
    CONSTRAINT FIDE_EMPLEADOS_ID_DIRECCION_FOREIGN_KEY FOREIGN KEY(idDireccion) REFERENCES FIDE_DIRECCIONES_TB(idDireccion),
    Salario NUMBER(10,2),
    Correo VARCHAR2(200),
    idEstado NUMBER, 
    CONSTRAINT FIDE_EMPLEADOS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    Contrasena VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_ROLES_TB(
    idRol NUMBER 
    CONSTRAINT FIDE_ROLES_ID_ROL_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    idEmpleado  NUMBER, 
    CONSTRAINT FIDE_ROLES_IDEMPLEADO_FOREIGN_KEY FOREIGN KEY(idEmpleado) REFERENCES FIDE_EMPLEADOS_TB(idEmpleado),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_ROLES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));

CREATE TABLE FIDE_VENTAS_TB(
    idVenta NUMBER 
    CONSTRAINT FIDE_VENTAS_TB_ID_VENTA_IDX PRIMARY KEY,
    idEmpleado NUMBER, 
    CONSTRAINT FIDE_VENTAS_ID_EMPLEADO_FOREIGN_KEY FOREIGN KEY(idEmpleado) REFERENCES FIDE_EMPLEADOS_TB(idEmpleado),
    idSucursal NUMBER, 
    CONSTRAINT FIDE_VENTAS_ID_SUCURSAL_FOREIGN_KEY FOREIGN KEY(idSucursal) REFERENCES FIDE_SUCURSALES_TB(idSucursal),
    fechaVenta DATE,
    Total NUMBER(10,2),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_VENTAS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_DETALLEVENTAS_TB(
    idDetalle NUMBER 
    CONSTRAINT FIDE_DETALLEVENTAS_TB_ID_DETALLE_IDX PRIMARY KEY,
    idVenta NUMBER, 
    CONSTRAINT FIDE_DETALLEVENTAS_ID_VENTA_FOREIGN_KEY FOREIGN KEY(idVenta) REFERENCES FIDE_VENTAS_TB(idVenta),
    idProducto NUMBER, 
    CONSTRAINT FIDE_PRODUCTOS_ID_PRODUCTO_FOREIGN_KEY FOREIGN KEY(idProducto) REFERENCES FIDE_PRODUCTOS_TB(idProducto),
    Cantidad NUMBER,
    precioUnitario NUMBER(10,2),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_DETALLEVENTAS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)

CREATE TABLE FIDE_METODOSPAGO_TB(
    idMetodoPago NUMBER 
    CONSTRAINT FIDE_METODOSPAGO_ID_METODOPAGO_IDX PRIMARY KEY,
    Nombre VARCHAR2(200),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_METODOSPAGO_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_FACTURAS_TB(
    idFactura NUMBER 
    CONSTRAINT FIDE_FACTURAS_ID_FACTURA_IDX PRIMARY KEY,
    idVenta NUMBER, 
    CONSTRAINT FIDE_FACTURAS_ID_VENTA_FOREIGN_KEY FOREIGN KEY(idVenta) REFERENCES FIDE_VENTAS_TB(idVenta),
    fechaEmision DATE,
    idMetodoPago NUMBER, 
    CONSTRAINT FIDE_FACTURAS_ID_METODOPAGO_FOREIGN_KEY FOREIGN KEY(idMetodoPago) REFERENCES FIDE_METODOSPAGO_TB(idMetodoPago),
    Subtotal NUMBER(10,2),
    Impuesto NUMBER(10,2),
    Total NUMBER(10,2),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_FACTURAS_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)
    
CREATE TABLE FIDE_DEVOLUCIONES_TB(
    idDevolucion NUMBER 
    CONSTRAINT FIDE_DEVOLUCIONES_ID_DEVOLUCION_IDX PRIMARY KEY,
    idProducto NUMBER, 
    CONSTRAINT FIDE_DEVOLUCIONES_ID_PRODUCTO_FOREIGN_KEY FOREIGN KEY(idProducto) REFERENCES FIDE_PRODUCTOS_TB(idProducto),
    idFactura NUMBER, 
    CONSTRAINT FIDE_DEVOLUCIONES_ID_FACTURA_FOREIGN_KEY FOREIGN KEY(idFactura) REFERENCES FIDE_FACTURAS_TB(idFactura),
    Fecha DATE,
    Motivo VARCHAR2(1000),
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    idEstado NUMBER, 
    CONSTRAINT FIDE_DEVOLUCIONES_ID_ESTADO_FOREIGN_KEY FOREIGN KEY(idEstado) REFERENCES FIDE_ESTADOS_TB(idEstado),
    ACCION VARCHAR2(100));
    ---(Exito)






--
--      Creación de Secuencias
--
----------------TABLA 1: CATEGORIAS----------------
CREATE SEQUENCE  ID_CATEGORIAS_SEQ
START WITH 1
INCREMENT BY 1;
-- (Exito)

----------------TABLA 2: ESTADOS----------------
CREATE SEQUENCE ID_ESTADOS_SEQ
START WITH 1
INCREMENT BY 1;
-- (Exito)

----------------TABLA 3: PAISES----------------
------------SECUENCIA PARA PAISES--------------
CREATE SEQUENCE ID_PAISES_SEQ
START WITH 1
INCREMENT BY 1;
-- (Exito)
----------------TABLA 4: PROVINCIAS----------------
------------SECUENCIA PARA PROVINCIAS--------------
CREATE SEQUENCE ID_PROVINCIAS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 5: CANTONES----------------
------------SECUENCIA PARA CANTONES--------------
CREATE SEQUENCE ID_CANTONES_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 6: DISTRITOS----------------
------------SECUENCIA PARA DISTRITOS--------------
CREATE SEQUENCE ID_DISTRITOS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)
----------------TABLA 7: DIRECCIONES----------------
------------SECUENCIA PARA DIRECCIONES--------------
CREATE SEQUENCE ID_DIRECCIONES_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)
----------------TABLA 8: PROVEEDORES----------------
------------SECUENCIA PARA PROVEEDORES--------------
CREATE SEQUENCE ID_PROVEEDORES_SEQ
START WITH 1
INCREMENT BY 1;
-- (Exito)
----------------TABLA 9: MARCAS PRODUCTOS----------------
------------SECUENCIA PARA MARCAS PRODUCTOS--------------
CREATE SEQUENCE ID_MARCASPRODUCTO_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)
----------------TABLA 10: PRODUCTOS----------------
-------------SECUENCIA PARA PRODUCTOS--------------
CREATE SEQUENCE ID_PRODUCTOS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)
----------------TABLA 11: PRODUCTOPROVEEDOR----------------
-------------SECUENCIA PARA PRODUCTOPROVEEDOR--------------
CREATE SEQUENCE ID_PRODUCTOPROVEEDOR_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 12: SUCURSALES----------------
-------------SECUENCIA PARA SUCURSALES--------------
CREATE SEQUENCE ID_SUCURSALES_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 13: INVENTARIOS----------------
-------------SECUENCIA PARA INVENTARIOS--------------
CREATE SEQUENCE ID_INVENTARIOS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 14: EMPLEADOS----------------
-------------SECUENCIA PARA EMPLEADOS--------------
CREATE SEQUENCE ID_EMPLEADOS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 15: VENTAS----------------
-------------SECUENCIA PARA VENTAS--------------
CREATE SEQUENCE ID_VENTAS_SEQ 
START WITH 1 
INCREMENT BY 1;
-- (Exito)
----------------TABLA 16: DETALLEVENTAS----------------
------------SECUENCIA PARA DETALLEVENTAS--------------
CREATE SEQUENCE ID_DETALLEVENTAS_SEQ
START WITH 1
INCREMENT BY 1;
-- (Exito)
----------------TABLA 17: METODOSPAGO----------------
-------------SECUENCIA PARA METODOSPAGO--------------
CREATE SEQUENCE ID_METODOSPAGO_SEQ  
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 18: FACTURAS----------------
-------------SECUENCIA PARA FACTURAS--------------
CREATE SEQUENCE ID_FACTURAS_SEQ  
START WITH 1 
INCREMENT BY 1;
-- (Exito)


----------------TABLA 19: DEVOLUCIONES----------------
-------------SECUENCIA PARA DEVOLUCIONES--------------  
CREATE SEQUENCE ID_DEVOLUCIONES_SEQ  
START WITH 1 
INCREMENT BY 1;
-- (Exito)

----------------TABLA 20: ROLES----------------
-------------SECUENCIA PARA ROLES--------------
CREATE SEQUENCE ID_ROLES_SEQ  
START WITH 1 
INCREMENT BY 1;
-- (Exito)


