DECLARE
     v_iddireccion fide_direcciones_tb.iddireccion%TYPE;
BEGIN
    fide_proyecto_final_pkg.fide_estados_tb_insertar_sp('Inactivo');
    fide_proyecto_final_pkg.fide_estados_tb_insertar_sp('Activo');

    fide_proyecto_final_pkg.fide_paises_tb_insertar_sp('Costa Rica');

    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Cartago', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('San José', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Alajuela', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Heredia', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Limón', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Puntarenas', 1);
    fide_proyecto_final_pkg.fide_provincias_tb_insertar_sp('Guanacaste', 1);

    -- Inserción de cantones por provincia
    -- Cartago
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Cartago', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Paraíso', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('La Unión', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Jiménez', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Turrialba', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Alvarado', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Oreamuno', 1);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('El Guarco', 1);

    -- San José
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San José', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Escazú', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Desamparados', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Puriscal', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Tarrazú', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Aserrí', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Mora', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Goicoechea', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Santa Ana', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Alajuelita', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Vázquez de Coronado', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Acosta', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Tibás', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Moravia', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Montes de Oca', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Turrubares', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Dota', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Curridabat', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Pérez Zeledón', 2);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('León Cortés Castro', 2);

    -- Alajuela
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Alajuela', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Ramón', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Grecia', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Mateo', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Atenas', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Naranjo', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Palmares', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Poás', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Orotina', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Carlos', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Zarcero', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Sarchí', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Upala', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Los Chiles', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Guatuso', 3);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Río Cuarto', 3);

    -- Heredia
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Heredia', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Barva', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Santo Domingo', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Santa Bárbara', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Rafael', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Isidro', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Belén', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Flores', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('San Pablo', 4);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Sarapiquí', 4);

    -- Limón
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Limón', 5);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Pococí', 5);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Siquirres', 5);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Talamanca', 5);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Matina', 5);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Guácimo', 5);

    -- Puntarenas
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Puntarenas', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Esparza', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Buenos Aires', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Montes de Oro', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Osa', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Quepos', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Golfito', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Coto Brus', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Parrita', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Corredores', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Garabito', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Monteverde', 6);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Puerto Jiménez', 6);

    -- Guanacaste
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Liberia', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Nicoya', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Santa Cruz', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Bagaces', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Carillo', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Cañas', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Abangares', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Tilarán', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Nandayure', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('La Cruz', 7);
    fide_proyecto_final_pkg.fide_cantones_tb_insertar_sp('Hojancha', 7);



    -- Inserción de distritos por cantón
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Oriental',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Occidental',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carmen',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Nicolas',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Aguacaliente',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guadalupe',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Corralillo',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tierra Blanca',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Dulce Nombre',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Llano Grande',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quebradilla',1);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Paraiso',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santiago',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Orosi',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cachi',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Llanos de Santa Lucia',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Birrisito',2);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tres Rios',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Diego',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Dulce Nombre',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Ramon',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Azul',3);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Juan Vinas',4);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tucurrique',4);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pejibaye',4);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Victoria',4);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Turrialba',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Suiza',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Peralta',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Cruz',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Teresita',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pavones',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tuis',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tayutic',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rosa',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tres Equis',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Isabel',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Chirripo',5);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pacayas',6);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cervantes',6);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Capellades',6);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',7);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cot',7);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Potrero Cerrado',7);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cipreses',7);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rosa',7);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Tejar',8);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',8);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tobosi',8);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Patio de Agua',8);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carmen',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Merced',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Hospital',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Catedral',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zapote',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Francisco de Dos Rios',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Uruca',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mata Redonda',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pavas',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Hatillo',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Sebastian',9);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Escazu',10);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',10);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',10);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Desamparados',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Miguel',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan de Dios',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael Arriba',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Frailes',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Patarra',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Cristobal',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rosario',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Damas',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael Abajo',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Gravilias',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Los Guido',11);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santiago',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mercedes Sur',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Barbacoas',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Grifo Alto',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Candelarita',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Desamparaditos',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Chires',12);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Marcos',13);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Lorenzo',13);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Carlos',13);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Aserri',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tarbaca',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Vuelta de Jorco',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Gabriel',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Legua',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Monterrey',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Salitrillos',14);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Colon',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guayabo',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tabarcia',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Piedras Negras',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Picagres',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jaris',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quitirrisi',15);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guadalupe',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Francisco',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Calle Blancos',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mata de Platano',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Ipis',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rancho Redondo',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Purral',16);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Ana',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Salitral',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pozos',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Uruca',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Piedades',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Brasil',17);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Alajuelita',18);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Josecito',18);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',18);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',18);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Felipe',18);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',19);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',19);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Dulce Nombre de Jesus',19);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Patalillo',19);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cascajal',19);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Ignacio',20);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guaitil',20);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmichal',20);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cangrejal',20);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sabanillas',20);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',21);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cinco Esquinas',21);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Anselmo llorente',21);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Leon XIII',21);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Colima',21);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Vicente',22);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jeronimo',22);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Trinidad',22);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',23);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sabanilla',23);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mercedes',23);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',23);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pablo',24);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',24);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan de Mata',24);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Luis',24);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carara',24);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Maria',25);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jardin',25);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Copey',25);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Curridabat',26);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Granadilla',26);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sanchez',26);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tirrases',26);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro de El General',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El General',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Daniel Flores',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rivas',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Platanares',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pejibaye',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cajon',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Baru',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Nuevo',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Paramo',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Amistad',27);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pablo',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Andres',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Llano Bonito',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Cruz',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',28);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Alajuela',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carrizal',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guacima',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sabanilla',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Segundo',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Desamparados',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Turrucares',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tambor',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Garita',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sarapiqui',29);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Ramon',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santiago',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Piedades Norte',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Piedades Sur',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Angeles',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Alfaro',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Volio',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zapotal',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Penas Blancas',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Lorenzo',30);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Grecia',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Roque',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tacares',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puente de Piedra',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bolivar',31);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Mateo',32);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Desmonte',32);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jesus Maria',32);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Labrador',32);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Atenas',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jesus',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mercedes',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Eulalia',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Escobal',33);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Naranjo',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Miguel',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cirri Sur',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jeronimo',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Rosario',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmitos',34);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmares',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zaragoza',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Buenos Aires',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santiago',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Candelaria',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Esquipulas',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Granja',35);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',36);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',36);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',36);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carrillos',36);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sabana Redonda',36);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Orotina',37);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Mastate',37);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Hacienda Vieja',37);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Coyolar',37);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Ceiba',37);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quesada',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Florencia',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Buenavista',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Aguas Zarcas',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Venecia',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pital',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Fortuna',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Tigra',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Palmera',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Venado',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cutris',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Monterrey',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pocosol',38);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zarcero',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Laguna',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tapesco',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guadalupe',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmira',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zapote',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Brisas',39);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sarchi Norte',40);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sarchi Sur',40);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Toro Amarillo',40);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',40);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rodriguez',40);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Upala',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Aguas Claras',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose(Pizote)',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bijagua',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Delicias',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Dos Rios',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Yolillal',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Canalete',41);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Los Chiles',42);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cano Negro',42);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Amparo',42);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jorge',42);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',43);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Buenavista',43);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cote',43);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Katira',43);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Cuarto',44);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rita',44);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Isabel',44);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Heredia',45);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mercedes',45);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Francisco',45);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Ulloa',45);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Varablanca',45);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Barva',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pablo',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Roque',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Lucia',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose de la Montana',46);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santo Domingo',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Vicente',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Miguel',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Paracito',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santo Tomas',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rosa',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tures',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Para',47);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Barbara',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pedro',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jesus',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santo Domingo',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puraba',48);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',49);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Josecito',49);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santiago',49);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Angeles',49);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',49);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',50);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jose',50);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Concepcion',50);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Francisco',50);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',51);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Ribera',51);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Asuncion',51);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Joaquin',52);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Barrantes',52);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Llorente',52);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pablo',53);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rincon de Sabanilla',53);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puerto Viejo',54);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Virgen',54);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Horquetas',54);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Llanuras del Gaspar',54);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Curena',54);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Limon',55);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Valle La Estrella',55);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Blanco',55);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Matama',55);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guapiles',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jimenez',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Rita',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Roxana',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cariari',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Colorado',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Colonia',56);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Siquirres',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pacuarito',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Florida',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Germania',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Cairo',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Alegria',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Reventazon',57);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bratsi',58);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sixaola',58);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cahuita',58);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Telire',58);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Matina',59);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Batan',59);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carrandi',59);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guacimo',60);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mercedes',60);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pocora',60);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Jimenez',60);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Duacari',60);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puntarenas',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pitahaya',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Chomes',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Lepanto',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Paquera',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Manzanillo',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guacimal',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Barranca',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Isla del Coco',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cobano',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Chacarita',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Chira',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Acapulco',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('El Roble',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Arancibia',61);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Espiritu Santo',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan Grande',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Macacona',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Rafael',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Jeroimo',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Caldera',62);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Buenos Aires',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Volcan',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Potrero Grande',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Boruca',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pilas',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Colinas',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Changuena',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Biolley',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Brunka',63);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Miramar',64);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Union',64);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Isidro',64);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puerto Cortes',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmar',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sierpe',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bahia Ballena',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Piedras Blancas',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bahia Drake',65);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quepos',66);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Savegre',66);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Naranjito',66);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Golfito',67);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Guaycar ',67);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pavon',67);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Vito',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sabalito',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Aguabuena',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Limoncito',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Pittier',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Gutierrez Braun',68);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Parrita',69);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Corredor',70);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Cuesta',70);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Canoas',70);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Laurel',70);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Jaco',71);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tarcoles',71);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Lagunillas',71);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Monteverde',72);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puerto Jimenez',73);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Liberia',74);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Canas Dulces',74);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mayorga',74);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Nacascolo',74);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Curubando',74);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Nicoya',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mansion',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Antonio',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quebrada Honda',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Samara',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Nosara',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Belen de Nosarita',75);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Cruz',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bolson',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Veintisiete de Abril',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tempate',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cartagena',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cuajiniquil',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Diria',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cabo Velas',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tamarindo',76);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bagaces',77);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Fortuna',77);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Mogote',77);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Rio Naranjo',77);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Filadelfia',78);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmira',78);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sardinal',78);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Belen',78);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Canas',79);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Palmira',79);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Miguel',79);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bebedero',79);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Porozal',79);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Las Juntas',80);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Sierra',80);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Juan',80);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Colorado',80);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tilaran',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Quebrada Grande',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tronadora',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rosa',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Libano',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Tierras Morenas',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Arenal',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Cabeceras',81);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Carmona',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Rita',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Zapotal',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('San Pablo',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Porvenir',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Bejuco',82);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Cruz',83);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Cecilia',83);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('La Garita',83);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Santa Elena',83);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Hojancha',84);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Monte Romo',84);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Puerto Carrillo',84);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Huacas',84);
    fide_proyecto_final_pkg.fide_distritos_tb_insertar_sp('Matambe',84);



    -- Datos claves

    fide_proyecto_final_pkg.fide_direcciones_tb_insertar_sp(1, 2, 23, 143, '200 metros sur del Outlet Mall', v_iddireccion);

    fide_proyecto_final_pkg.fide_sucursales_tb_insertar_sp('Sucursal Central', 1, '8:00am', '5:00pm');

    fide_proyecto_final_pkg.fide_empleados_tb_insertar_sp('Nathalie Poveda Chaves', 1, 'Gerente de Cajas', 1, 1500, 'nathalie@innovatech.com', '123');

    fide_proyecto_final_pkg.fide_roles_tb_insertar_sp('ROLE_ADMIN', 1);
    
    fide_proyecto_final_pkg.fide_categorias_tb_insertar_sp('Procesadores', 'Procesador de computador');
    
    fide_proyecto_final_pkg.fide_marcasproducto_tb_insertar_sp('AMD');
    
    fide_proyecto_final_pkg.fide_productos_tb_insertar_sp('Ryzen 7 5700 X3D', 150, 1,1); 
    
    fide_proyecto_final_pkg.fide_inventarios_tb_insertar_sp(1,5,1);

    fide_proyecto_final_pkg.fide_metodospago_tb_insertar_sp('Tarjeta');
    fide_proyecto_final_pkg.fide_metodospago_tb_insertar_sp('Efectivo');
    fide_proyecto_final_pkg.fide_metodospago_tb_insertar_sp('SINPE Movil');
    
    fide_proyecto_final_pkg.fide_ventas_tb_insertar_sp(1,1, SYSDATE, 150);
    fide_proyecto_final_pkg.fide_detalleventas_tb_insertar_sp(1, 1,1,150);
    fide_proyecto_final_pkg.fide_facturas_tb_insertar_sp(1,SYSDATE,1,150,0.15, 152);
    
    fide_proyecto_final_pkg.fide_devoluciones_tb_insertar_sp(1,1, SYSDATE, 'Defecto de fabrica');
 
END;
/