-- Insertar en FIDE_CATEGORIAS_TB
INSERT INTO FIDE_CATEGORIAS_TB (idCategoria, Nombre, Descripcion, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Electrónica', 'Productos electrónicos como teléfonos, computadoras, televisores, etc.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_ESTADOS_TB
INSERT INTO FIDE_ESTADOS_TB (idEstado, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Disponible', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_PAISES_TB
INSERT INTO FIDE_PAISES_TB (idPais, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Costa Rica', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_PROVINCIAS_TB
INSERT INTO FIDE_PROVINCIAS_TB (idProvincia, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'San José', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_CANTONES_TB
INSERT INTO FIDE_CANTONES_TB (idCanton, Nombre, FECHA_CREACION, CREADO_POR, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'San José', SYSTIMESTAMP, 'admin', 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_DISTRITOS_TB
INSERT INTO FIDE_DISTRITOS_TB (idDistrito, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Carmen', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_DIRECCIONES_TB
INSERT INTO FIDE_DIRECCIONES_TB (idDireccion, idPais, idProvincia, idCanton, idDistrito, direccionExacta, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 1, 1, 1, 1, 'Avenida Central, San José, Costa Rica', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_PROVEEDORES_TB
INSERT INTO FIDE_PROVEEDORES_TB (idProveedor, Nombre, idDireccion, Telefono, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Proveedor A', 1, 25467890, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_MARCASPRODUCTO_TB
INSERT INTO FIDE_MARCASPRODUCTO_TB (idMarca, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'MarcaX', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_PRODUCTOS_TB
INSERT INTO FIDE_PRODUCTOS_TB (idProducto, Nombre, Precio, idCategoria, idEstado, idMarca, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Teléfono Móvil', 199.99, 1, 1, 1, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_PRODUCTOPROVEEDOR_TB
INSERT INTO FIDE_PRODUCTOPROVEEDOR_TB (idProductoProveedor, horarioEntrega, idProveedor, precioCompra, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Lunes a Viernes 9:00 AM - 5:00 PM', 1, 150.00, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_SUCURSALES_TB
INSERT INTO FIDE_SUCURSALES_TB (idSucursal, Nombre, idDireccion, horaApertura, horaCierre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Sucursal Central', 1, '8:00 AM', '6:00 PM', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_INVENTARIOS_TB
INSERT INTO FIDE_INVENTARIOS_TB (idInventario, idProducto, Cantidad, ultimaActualizacion, idSucursal, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 1, 100, SYSDATE, 1, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_EMPLEADOS_TB
INSERT INTO FIDE_EMPLEADOS_TB (idEmpleado, Nombre, idSucursal, Puesto, idDireccion, Salario, Correo, idEstado, Contrasena, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Juan Pérez', 1, 'Vendedor', 1, 1200.00, 'juan@empresa.com', 1, 'password123', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_ROLES_TB
INSERT INTO FIDE_ROLES_TB (idRol, Nombre, idEmpleado, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'ROLE_ADMIN', 1, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_VENTAS_TB
INSERT INTO FIDE_VENTAS_TB (idVenta, idEmpleado, idSucursal, fechaVenta, Total, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 1, 1, SYSDATE, 199.99, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_DETALLEVENTAS_TB
INSERT INTO FIDE_DETALLEVENTAS_TB (idDetalle, idVenta, idProducto, Cantidad, precioUnitario, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 1, 1, 1, 199.99, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_METODOSPAGO_TB
INSERT INTO FIDE_METODOSPAGO_TB (idMetodoPago, Nombre, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 'Tarjeta de Crédito', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar en FIDE_FACTURAS_TB
INSERT INTO FIDE_FACTURAS_TB (idFactura, idVenta, fechaEmision, idMetodoPago, Subtotal, Impuesto, Total, CREADO_POR, FECHA_CREACION, MODIFICADO_POR, FECHA_MODIFICACION, ESTADO, ACCION)
VALUES (1, 1, SYSDATE, 1, 199.99, 19.99, 219.98, 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'A', 'insertar');

-- Insertar
