
DROP PROCEDURE FIDE_ESTADOS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_PAISES_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_PROVINCIAS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_CANTONES_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_DISTRITOS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_DIRECCIONES_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_PROVEEDORES_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_MARCASPRODUCTO_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_PRODUCTOS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_PRODUCTOPROVEEDOR_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_SUCURSALES_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_INVENTARIOS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_EMPLEADOS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_VENTAS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_DETALLEVENTAS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_METODOSPAGO_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_FACTURAS_TB_INSERTAR_SP;
DROP PROCEDURE FIDE_DEVOLUCIONES_TB_INSERTAR_SP;

-- Llamada a FIDE_ESTADOS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_TB_INSERTAR_SP(7, 'Activo');

-- Llamada a FIDE_PAISES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_PAISES_TB_INSERTAR_SP(6, 'Costa Rica');

-- Llamada a FIDE_PROVINCIAS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIAS_TB_INSERTAR_SP(7, 'Provincia A');

-- Llamada a FIDE_CANTONES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_CANTONES_TB_INSERTAR_SP(7, 'Puriscal');

-- Llamada a FIDE_DISTRITOS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITOS_TB_INSERTAR_SP(7, 'Mercedes Sur');

-- Llamada a FIDE_DIRECCIONES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_DIRECCIONES_TB_INSERTAR_SP(7, 7, 7, 7, 7, 'Cerbatana, Urbanización Miramar');

-- Llamada a FIDE_PROVEEDORES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_PROVEEDORES_TB_INSERTAR_SP(7, 'Hp', 7, 24171032);

-- Llamada a FIDE_MARCASPRODUCTO_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_MARCASPRODUCTO_TB_INSERTAR_SP(7, 'Hp');

-- Llamada a FIDE_PRODUCTOS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_PRODUCTOS_TB_INSERTAR_SP(3, 'Hp Pavilion', 3500 , 1, 1, 1);

-- Llamada a FIDE_PRODUCTOPROVEEDOR_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_PRODUCTOPROVEEDOR_TB_INSERTAR_SP(7, 'lunes 9 am', 7, 35000);

-- Llamada a FIDE_SUCURSALES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_SUCURSALES_TB_INSERTAR_SP(7, 'Sucursal Puriscal', 7, '08:00', '16:00');

-- Llamada a FIDE_INVENTARIOS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_INVENTARIOS_TB_INSERTAR_SP(7, 1, 240, SYSDATE, 1);

-- Llamada a FIDE_EMPLEADOS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_EMPLEADOS_TB_INSERTAR_SP(7, 'Sofía Sancho', 7, 'Gerente', 7, 150000, 'sofiasancho0219@innovatech.com', 7);

-- Llamada a FIDE_VENTAS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_VENTAS_TB_INSERTAR_SP(7, 7, 7, SYSDATE, 20000);

-- Llamada a FIDE_DETALLEVENTAS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_DETALLEVENTAS_TB_INSERTAR_SP(7, 1, 1, 1, 10000);

-- Llamada a FIDE_METODOSPAGO_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_METODOSPAGO_TB_INSERTAR_SP(7, 'Efectivo');

-- Llamada a FIDE_FACTURAS_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_FACTURAS_TB_INSERTAR_SP(7, 7, SYSDATE, 7, 35000, 35400, 400);

-- Llamada a FIDE_DEVOLUCIONES_TB_INSERTAR_SP
EXEC FIDE_PROYECTO_FINAL_PKG.FIDE_DEVOLUCIONES_TB_INSERTAR_SP(7, 1, 1, SYSDATE, 'PC con pantallas rayada');


