---------PRUEBA DE FUNCIONES DENTRO DEL PAQUETE

SELECT FIDE_PROYECTO_FINAL_PKG.CATEGORIAS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.ESTADOS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.PAISES_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.PROVINCIAS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.CANTONES_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.DISTRITOS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.PROVEEDORES_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.MARCASPRODUCTO_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.PRODUCTOS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.PRODUCTOPROVEEDOR_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.SUCURSALES_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.INVENTARIOS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.EMPLEADOS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.VENTAS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.DETALLEVENTAS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.METODOSPAGO_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.FACTURAS_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.DEVOLUCIONES_GENERAR_SECUENCIA_FN FROM DUAL;
SELECT FIDE_PROYECTO_FINAL_PKG.ROLES_GENERAR_SECUENCIA_FN FROM DUAL;