alter session set "_ORACLE_SCRIPT"= true;

CREATE ROLE admin_role;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE SEQUENCE TO admin_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_CANTONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_CATEGORIAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DETALLEVENTAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DEVOLUCIONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DIRECCIONES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_DISTRITOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_EMPLEADOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_ESTADOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_FACTURAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_INVENTARIOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_MARCASPRODUCTO_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_METODOSPAGO_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PAISES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PRODUCTOPROVEEDOR_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PRODUCTOS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PROVEEDORES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_PROVINCIAS_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_ROLES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_SUCURSALES_TB TO admin_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_VENTAS_TB TO admin_role;


CREATE USER usuario1 IDENTIFIED BY "123";
GRANT admin_role to usuario1;
